JunctionProject/force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JunctionProject/force-app/main/default/objects/Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

JunctionProject/force-app/main/default/objects/Agreement__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

JunctionProject/force-app/main/default/objects/Agreement_Product_Junction__c/Agreement_Product_Junction__c.object-meta.xml
<CustomObject>
    <label>Agreement Product</label>
    <nameField>
        <label>Agreement Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JunctionProject/force-app/main/default/objects/Agreement_Product_Junction__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>Agreement__c</referenceTo>
    <relationshipLabel>Agreement Products</relationshipLabel>
    <relationshipName>Agreement_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

JunctionProject/force-app/main/default/objects/Agreement_Product_Junction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Agreement Products</relationshipLabel>
    <relationshipName>Agreement_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

JunctionProject/force-app/main/default/objects/Agreement_Product_Junction__c/fields/Product_code__c.field-meta.xml
<CustomField>
    <fullName>Product_code__c</fullName>
    <formula>Product__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product code</label>
    <type>Text</type>
</CustomField>

JunctionProject/force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    private TestDataFactory() {}

    public static User createAdminUser() {
        Profile prof = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User user = new User(Username = 'test3453User345@testtt.com', IsActive = true, ProfileId = prof.Id, Alias = 'testU',
                        email = 'test123@mail.com', LastName = 'test', TimeZoneSidKey = 'GMT', LocaleSidKey = 'en_US',
                        EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US');
        try {
            insert user;
        } catch (DMLException dmle) {
            System.debug(dmle);
        }
        return user;
    }

    public static Account[] createAccounts(Integer accsNum) {
        Account[] accs = new List<Account>();
        for(Integer i = 0; i < accsNum; i++) {
            accs.add(new Account(Name = 'testAcc' + i));
        }

        insert accs;

        return accs;
    }

    public static Product2[] createProducts(Integer n) {
        Product2[] products = new List<Product2>();
        for (Integer i = 0; i < n; i++) {
            products.add(new Product2(Name = 'test' + i, ProductCode = 'NN111' + i, isActive = true));
        }
        insert products;
        return products;
    }

    public static Product2[] createProducts(String[] codes) {
        Product2[] products = new List<Product2>();
        for (String code : codes) {
            products.add(new Product2(Name = 'test' + code + 'test', ProductCode = code, isActive = true));
        }
        insert products;
        return products;
    }

    public static Agreement__c[] createAgreements(String[] productCodes, Id accId) {
        Agreement__c[] agrs = new List<Agreement__c>();
        for (Integer i = 0; i < productCodes.size(); i++) {
            agrs.add(new Agreement__c(Name = 'testAgr' + i, Account__c = accId, Products__c = productCodes[i]));
        }
        insert agrs;
        return agrs;
    }

    public static Agreement__c[] queryJunctionFromAgreement(Agreement__c[] agrs) {
        return [SELECT  Id, Products__c, (SELECT Product__c, Agreement__c, Product_code__c FROM Agreement_Products__r)
                FROM Agreement__c 
                WHERE Id IN :agrs];
    }


}